### PR TITLE
Add scijava-plugins-io-table dependency

### PR DESCRIPTION
**Pull request by imagejan**
See https://github.com/scijava/scijava-plugins-io-table/issues/4#issuecomment-452622956.

### CODE REVIEW

**Comment by ctrueden** [comment]
Sorry this slipped through the cracks!

**Comment by ctrueden** [comment]
The current Fiji does ship `scijava-plugins-io-table` at version 0.2.0, which is the latest release. And it doesn't look like that plugin has any new work on master (other than POM updates) since 0.2.0 was released.

@tferr I looked at tferr/ASA#30 but I don't understand how it relates to this issue here. The problem described in tferr/ASA#30 is the lack of buttons in the table UI, no? So we'd need to improve the Swing display viewer of SciJava tables, no? Or at least ensure there is a _File > Export > Table..._ command or some such? Seems very doable, but can we discuss the requirements a little before plunging ahead?

**Comment by tferr** [comment]
@ctrueden, sorry. I read the forum thread in haste and somehow thought `scijava-plugins-io-table` would extend the table display viewer. I should have paid more attention. Sorry about that. The requirements would be very loose: Just _something_  to save tables. Maybe a contextual menu? This is also affecting SNT that has a bunch of SciJava tables (for some I wrote a File>Save As> command that are called from the SNT GUI) so I can chime in. How do we go about it? If you give me some pointers, I can try to hack something.

**Comment by tferr** [comment]
@ctrueden I just realized the the proper issue to comment was https://github.com/imagej/imagej-common/issues/75 not this one. I guess this discussion should go there?

**Comment by ctrueden** [comment]
@tferr Let's continue the discussion at scijava/scijava-ui-swing#37, which I think is the issue covering what's needed here: a way to export tables from the UI.

**Pull request merged**
